### ISSUE TITLE
Fix broken example

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-acm-certificate#7]
In the example [Domain not hosted by Route53](https://github.com/techservicesillinois/terraform-aws-acm-certificate#domain-not-hosted-by-route53) the tags map is broken in Terraform v0.12:
```
tags { 
      environment = "test"
}
```
Instead it should be:
```
tags = { 
      environment = "test"
}
```
In addition the source lines have the unnecessary `git::`, `.git`, `?ref`, and `//`.

**Comment by JonRoma** [comment]
While it was difficult to sort out where the problem was (mentioning README.md would have helped), this was easy to fix; see pull request #8. All tests now pass.
